apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/viniciusog1/stockguardian:latest
          command: ["arq", "app.worker.settings.WorkerSettings"]
          envFrom:
            - configMapRef:
                name: stockguardian-config
            - secretRef:
                name: stockguardian-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
